### ISSUE TITLE
Deprecated selector in `firewatch-green-syntax/index.less`

### ISSUE THREAD

**Issue by felipebhz** [SebastianSzturo/firewatch-green-syntax#5]
Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .line.cursor-line,
:host .line.cursor-line` => `atom-text-editor .line.cursor-line,atom-text-editor .line.cursor-line`

* `atom-text-editor .invisible,
:host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .bracket-matcher .region,
:host .bracket-matcher .region` => `atom-text-editor .bracket-matcher .region,atom-text-editor .bracket-matcher .region`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .gutter .line-number,
:host .gutter .line-number` => `atom-text-editor .gutter .line-number,atom-text-editor .gutter .line-number`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number .icon-right,
:host .gutter .line-number .icon-right` => `atom-text-editor .gutter .line-number .icon-right,atom-text-editor .gutter .line-number .icon-right`

* `atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before,
:host .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before` => `atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before,atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before`

* `atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed::after,
:host .gutter:not(.git-diff-icon) .line-number.git-line-removed::after` => `atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed::after,atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed::after`

* `atom-text-editor .gutter .line-number.folded,
:host .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,
:host .gutter .line-number:after,
atom-text-editor .fold-marker:after,
:host .fold-marker:after` => `atom-text-editor .gutter .line-number.folded,atom-text-editor .gutter .line-number.folded,
atom-text-editor .gutter .line-number:after,atom-text-editor .gutter .line-number:after,
atom-text-editor .fold-marker:after,atom-text-editor .fold-marker:after`

* `.comment` => `.syntax--comment`

* `.comment .markup.link` => `.syntax--comment .syntax--markup.syntax--link`

* `.entity.name.type` => `.syntax--entity.syntax--name.syntax--type`

* `.entity.other.inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class`

* `.keyword` => `.syntax--keyword`

* `.keyword.control` => `.syntax--keyword.syntax--control`

* `.keyword.operator` => `.syntax--keyword.syntax--operator`

* `.keyword.other.special-method` => `.syntax--keyword.syntax--other.syntax--special-method`

* `.keyword.other.unit` => `.syntax--keyword.syntax--other.syntax--unit`

* `.storage` => `.syntax--storage`

* `.storage.type.annotation,
.storage.type.primitive` => `.syntax--storage.syntax--type.syntax--annotation,
.syntax--storage.syntax--type.syntax--primitive`

* `.storage.modifier.package,
.storage.modifier.import` => `.syntax--storage.syntax--modifier.syntax--package,
.syntax--storage.syntax--modifier.syntax--import`

* `.constant` => `.syntax--constant`

* `.constant.variable` => `.syntax--constant.syntax--variable`

* `.constant.character.escape` => `.syntax--constant.syntax--character.syntax--escape`

* `.constant.numeric` => `.syntax--constant.syntax--numeric`

* `.constant.other.color` => `.syntax--constant.syntax--other.syntax--color`

* `.constant.other.symbol` => `.syntax--constant.syntax--other.syntax--symbol`

* `.variable` => `.syntax--variable`

* `.variable.interpolation` => `.syntax--variable.syntax--interpolation`

* `.variable.parameter` => `.syntax--variable.syntax--parameter`

* `.string` => `.syntax--string`

* `.string.regexp` => `.syntax--string.syntax--regexp`

* `.string.regexp .source.ruby.embedded` => `.syntax--string.syntax--regexp .syntax--source.syntax--ruby.syntax--embedded`

* `.string.other.link` => `.syntax--string.syntax--other.syntax--link`

* `.punctuation.definition.comment` => `.syntax--punctuation.syntax--definition.syntax--comment`

* `.punctuation.definition.method-parameters,
.punctuation.definition.function-parameters,
.punctuation.definition.parameters,
.punctuation.definition.separator,
.punctuation.definition.seperator,
.punctuation.definition.array` => `.syntax--punctuation.syntax--definition.syntax--method-parameters,
.syntax--punctuation.syntax--definition.function-parameters,
.syntax--punctuation.syntax--definition.syntax--parameters,
.syntax--punctuation.syntax--definition.syntax--separator,
.syntax--punctuation.syntax--definition.syntax--seperator,
.syntax--punctuation.syntax--definition.syntax--array`

* `.punctuation.definition.heading,
.punctuation.definition.identity` => `.syntax--punctuation.syntax--definition.syntax--heading,
.syntax--punctuation.syntax--definition.syntax--identity`

* `.punctuation.definition.bold` => `.syntax--punctuation.syntax--definition.syntax--bold`

* `.punctuation.definition.italic` => `.syntax--punctuation.syntax--definition.syntax--italic`

* `.punctuation.section.embedded` => `.syntax--punctuation.syntax--section.syntax--embedded`

* `.punctuation.section.method,
.punctuation.section.class,
.punctuation.section.inner-class` => `.syntax--punctuation.syntax--section.syntax--method,
.syntax--punctuation.syntax--section.syntax--class,
.syntax--punctuation.syntax--section.syntax--inner-class`

* `.support.class` => `.syntax--support.syntax--class`

* `.support.type` => `.syntax--support.syntax--type`

* `.support.function` => `.syntax--support.syntax--function`

* `.support.function.any-method` => `.syntax--support.syntax--function.syntax--any-method`

* `.entity.name.function` => `.syntax--entity.syntax--name.syntax--function`

* `.entity.name.class,
.entity.name.type.class` => `.syntax--entity.syntax--name.syntax--class,
.syntax--entity.syntax--name.syntax--type.syntax--class`

* `.entity.name.section` => `.syntax--entity.syntax--name.syntax--section`

* `.entity.name.tag` => `.syntax--entity.syntax--name.syntax--tag`

* `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`

* `.entity.other.attribute-name.id` => `.syntax--entity.syntax--other.syntax--attribute-name.syntax--id`

* `.meta.class` => `.syntax--meta.syntax--class`

* `.meta.class.body` => `.syntax--meta.syntax--class.syntax--body`

* `.meta.method-call,
.meta.method` => `.syntax--meta.syntax--method-call,
.syntax--meta.syntax--method`

* `.meta.definition.variable` => `.syntax--meta.syntax--definition.syntax--variable`

* `.meta.link` => `.syntax--meta.syntax--link`

* `.meta.require` => `.syntax--meta.syntax--require`

* `.meta.selector` => `.syntax--meta.syntax--selector`

* `.meta.separator` => `.syntax--meta.syntax--separator`

* `.meta.tag` => `.syntax--meta.syntax--tag`

* `.underline` => `.syntax--underline`

* `.none` => `.syntax--none`

* `.invalid.deprecated` => `.syntax--invalid.syntax--deprecated`

* `.invalid.illegal` => `.syntax--invalid.syntax--illegal`

* `.markup.bold` => `.syntax--markup.syntax--bold`

* `.markup.changed` => `.syntax--markup.syntax--changed`

* `.markup.deleted` => `.syntax--markup.syntax--deleted`

* `.markup.italic` => `.syntax--markup.syntax--italic`

* `.markup.heading` => `.syntax--markup.syntax--heading`

* `.markup.heading .punctuation.definition.heading` => `.syntax--markup.syntax--heading .syntax--punctuation.syntax--definition.syntax--heading`

* `.markup.link` => `.syntax--markup.syntax--link`

* `.markup.inserted` => `.syntax--markup.syntax--inserted`

* `.markup.quote` => `.syntax--markup.syntax--quote`

* `.markup.raw` => `.syntax--markup.syntax--raw`

* `.source.cs .keyword.operator` => `.syntax--source.syntax--cs .syntax--keyword.syntax--operator`

* `.source.css .property-name,
.source.css .property-value` => `.syntax--source.syntax--css .syntax--property-name,
.syntax--source.syntax--css .syntax--property-value`

* `.source.css .property-name.support,
.source.css .property-value.support` => `.syntax--source.syntax--css .syntax--property-name.syntax--support,
.syntax--source.syntax--css .syntax--property-value.syntax--support`

* `.source.gfm .markup` => `.syntax--source.syntax--gfm .syntax--markup`

* `.source.gfm .link .entity` => `.syntax--source.syntax--gfm .syntax--link .syntax--entity`

* `.source.go .storage.type.string` => `.syntax--source.syntax--go .syntax--storage.syntax--type.syntax--string`

* `.source.ini .keyword.other.definition.ini` => `.syntax--source.syntax--ini .syntax--keyword.syntax--other.syntax--definition.syntax--ini`

* `.source.java .storage.modifier.import` => `.syntax--source.syntax--java .syntax--storage.syntax--modifier.syntax--import`

* `.source.java .storage.type` => `.syntax--source.syntax--java .syntax--storage.syntax--type`

* `.source.java-properties .meta.key-pair` => `.syntax--source.syntax--java-properties .syntax--meta.syntax--key-pair`

* `.source.java-properties .meta.key-pair > .punctuation` => `.syntax--source.syntax--java-properties .syntax--meta.syntax--key-pair > .syntax--punctuation`

* `.source.js .keyword.operator` => `.syntax--source.syntax--js .syntax--keyword.syntax--operator`

* `.source.js .keyword.operator.delete,
.source.js .keyword.operator.in,
.source.js .keyword.operator.of,
.source.js .keyword.operator.instanceof,
.source.js .keyword.operator.new,
.source.js .keyword.operator.typeof,
.source.js .keyword.operator.void` => `.syntax--source.syntax--js .syntax--keyword.syntax--operator.syntax--delete,
.syntax--source.syntax--js .syntax--keyword.syntax--operator.syntax--in,
.syntax--source.syntax--js .syntax--keyword.syntax--operator.syntax--of,
.syntax--source.syntax--js .syntax--keyword.syntax--operator.syntax--instanceof,
.syntax--source.syntax--js .syntax--keyword.syntax--operator.syntax--new,
.syntax--source.syntax--js .syntax--keyword.syntax--operator.typeof,
.syntax--source.syntax--js .syntax--keyword.syntax--operator.syntax--void`

* `.source.json .meta.structure.dictionary.json > .string.quoted.json` => `.syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary.syntax--json > .syntax--string.syntax--quoted.syntax--json`

* `.source.json .meta.structure.dictionary.json > .string.quoted.json > .punctuation.string` => `.syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary.syntax--json > .syntax--string.syntax--quoted.syntax--json > .syntax--punctuation.syntax--string`

* `.source.json .meta.structure.dictionary.json > .value.json > .string.quoted.json,
.source.json .meta.structure.array.json > .value.json > .string.quoted.json,
.source.json .meta.structure.dictionary.json > .value.json > .string.quoted.json > .punctuation,
.source.json .meta.structure.array.json > .value.json > .string.quoted.json > .punctuation` => `.syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary.syntax--json > .syntax--value.syntax--json > .syntax--string.syntax--quoted.syntax--json,
.syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--array.syntax--json > .syntax--value.syntax--json > .syntax--string.syntax--quoted.syntax--json,
.syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary.syntax--json > .syntax--value.syntax--json > .syntax--string.syntax--quoted.syntax--json > .syntax--punctuation,
.syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--array.syntax--json > .syntax--value.syntax--json > .syntax--string.syntax--quoted.syntax--json > .syntax--punctuation`

* `.source.json .meta.structure.dictionary.json > .constant.language.json,
.source.json .meta.structure.array.json > .constant.language.json` => `.syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--dictionary.syntax--json > .syntax--constant.syntax--language.syntax--json,
.syntax--source.syntax--json .syntax--meta.syntax--structure.syntax--array.syntax--json > .syntax--constant.syntax--language.syntax--json`

* `.source.ruby .constant.other.symbol > .punctuation` => `.syntax--source.syntax--ruby .syntax--constant.syntax--other.syntax--symbol > .syntax--punctuation`

* `.source.python .keyword.operator.logical.python` => `.syntax--source.syntax--python .syntax--keyword.syntax--operator.syntax--logical.syntax--python`

* `.source.python .variable.parameter` => `.syntax--source.syntax--python .syntax--variable.syntax--parameter`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by tbremer** [comment]
I think #4 resolves this.

**Comment by SebastianSzturo** [comment]
I missed that PR. Sorry about that, merging now and releasing a new version today! 👍
